spring.application.name=TouristGuide_2
spring.datasource.url=jdbc:mysql://localhost:3306/tourist_guide?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Morp#freja22!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.profiles.active=dev